### PR TITLE
Simplify Java client error-handling example

### LINKED ISSUE #747: application-gateway-java not working
Following the basic instruction from https://hyperledger-fabric.readthedocs.io/en/latest/write_first_app.html
And using the java chaincode:
./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-java/ -ccl java

The asset-transfer-basic/application-gateway-java application fails endorsing the transaction with this error:

```
org.hyperledger.fabric.client.EndorseException: io.grpc.StatusRuntimeException: ABORTED: failed to endorse transaction, see attached details for more info
    at org.hyperledger.fabric.client.GatewayClient.endorse (GatewayClient.java:57)
    at org.hyperledger.fabric.client.ProposalImpl.endorse (ProposalImpl.java:71)
    at org.hyperledger.fabric.client.ContractImpl.submitTransaction (ContractImpl.java:38)
    at App.initLedger (App.java:150)
    at App.run (App.java:124)
    at App.main (App.java:81)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:830)
Caused by: io.grpc.StatusRuntimeException: ABORTED: failed to endorse transaction, see attached details for more info
    at io.grpc.stub.ClientCalls.toStatusRuntimeException (ClientCalls.java:262)
    at io.grpc.stub.ClientCalls.getUnchecked (ClientCalls.java:243)
    at io.grpc.stub.ClientCalls.blockingUnaryCall (ClientCalls.java:156)
    at org.hyperledger.fabric.protos.gateway.GatewayGrpc$GatewayBlockingStub.endorse (GatewayGrpc.java:472)
    at org.hyperledger.fabric.client.GatewayClient.endorse (GatewayClient.java:55)
    at org.hyperledger.fabric.client.ProposalImpl.endorse (ProposalImpl.java:71)
    at org.hyperledger.fabric.client.ContractImpl.submitTransaction (ContractImpl.java:38)
    at App.initLedger (App.java:150)
    at App.run (App.java:124)
    at App.main (App.java:81)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:830)
```

Thoughts?

### PR DESCRIPTION
**Pull request by bestbeforetoday**
The latest fabric-gateway client API release (v1.7.0) includes the gRPC error details in the GatewayExcetion stack trace so it is not necessary to programmatically access them to demonstrate that they are present.

This change updates the asset-transfer-basic/application-gateway-java sample to simplify the updateNonExistentAsset example method. It also:

- Updates all samples to use the latest fabric-gateway release.
- Adds equivalent Maven POM files for fabric-gateway application samples.

The additional testing of running the Java client applications using first Gradle and then Maven identified an inconsistency in behaviour between the Java implementation of the asset-transfer-basic smart contract and all the other language implementations. In only the Java implementation, the InitLedger call failed if the assets already existed, which meant that the sample client applications could only be run once. A subsequent run (without clearing the ledger) resulted in an endorsement failure on the InitLedger call. This change fixes that behaviour and makes the Java implementation consistent with the other language implementations.

Closes #747

### CODE REVIEW

File: asset-transfer-basic/application-gateway-java/src/main/java/App.java [hunk 1]
```diff
@@ -231,20 +231,11 @@ private void updateNonExistentAsset() {
...
 			System.out.println("Transaction ID: " + e.getTransactionId());
-
-			var details = e.getDetails();
-			if (!details.isEmpty()) {
-				System.out.println("Error Details:");
-				for (var detail : details) {
-					System.out.println("- address: " + detail.getAddress() + ", mspId: " + detail.getMspId()
-							+ ", message: " + detail.getMessage());
-				}
-			}
```
Comment (denyeart) [inline asset-transfer-basic/application-gateway-java/src/main/java/App.java:245]: So glad we don't have to traverse the details now!

**Review by denyeart — APPROVED** [review]

File: asset-transfer-basic/application-gateway-java/src/main/java/App.java (hunk 1 above)
Comment (bestbeforetoday) [reply asset-transfer-basic/application-gateway-java/src/main/java/App.java:245]: You can still access them programmatically (as before) if you need to buy this gives a much smoother user experience when things go wrong. I'm wondering if there is anything that can be done better for Go too.
